### ISSUE TITLE
Different format support for one file export

### ISSUE THREAD

**Issue by OO00O0O** [onesky/api-documentation-platform#24] opened 2015-04-13 14:56 UTC
Add format selection to translation export for one file.
Currently there are none. You can download file only in default format you have uploaded.

**Comment by rubyluk** [comment] 2015-04-14 07:22
Hi thank you for the suggestion.

May I know any particular format conversions you need when using OneSky?
Would it be a one-off conversion or a constant difference on file formats between your imported files and translation files?

**Comment by BunnyHolder** [comment] 2015-04-15 07:45
Constant diff. PHP <-> JSON(node.js applications) would be nice and PHP<-> YAML(symfony2).

**Comment by QuadRatNewBy** [comment] 2015-05-06 07:00
Just adding my two cents.
Every file looks like "Key-Value Pair" (At least those that I've saw). So I think it would be great to have ability to download translation in simplest format - 'key' = 'value' (Similar to `INI` or `TEXT_INI` formats).
Having this in hands one can easily write their own custom converter (even to 'non-onesky' formats).

**Comment by vanniktech** [comment] 2015-09-24 09:17
+1 what's the status for this one, currently I can only download the files in the format of iOS. I want to be able to download them in the Android format (XML) though.

**Comment by mickaelbeaudry** [comment] 2015-11-25 20:48
+1 on @vanniktech's comment, same here

**Comment by TriPhoenix** [comment] 2016-06-01 09:55
I'd like to +1 this issue as well; in our specific case the original data is an xlsx file while we need an iOS .strings export; Unfortunately I cannot even download them as .xlsx right now as those are supposedly not downloadable through the API (error message).

**Comment by FranzBusch** [comment] 2016-09-30 11:57
+1 same here

**Comment by ab9-er** [comment] 2017-10-16 13:13
Facing the same issue, guess it is still open after 2 years without any resolution. Any updates @rubyluk  ?

**Comment by timothycosta** [comment] 2018-02-07 05:31
Same issue.  We would like to share strings between ios and android, but can only download `.strings` via the API.

**Comment by mrnnn** [comment] 2018-04-03 09:48
+1 here. simply because I18NEXT_HIERARCHICAL_JSON does not fill out fallbacks (contrary to documentation), so I want to export using that instead of the default HIERARCHICAL_JSON.

The closest I can get today is export to I18NEXT_MULTILINGUAL_JSON, which will not fill out fallbacks (we want to do fallbacks ourselves because we don't want to fallback straight from fr-FR -> base language, instead, we want to go from fr-FR to fr to en to base) and then split up. That's not working well for us.

**Comment by mrnnn** [comment] 2018-04-03 09:49
By the way, this is a duplicate of #7

**Comment by mtter** [comment] 2018-05-28 16:29
Same/similar problem here: File format (.csv (Comma Separated Values)) is not downloadable through API

**Comment by XplittR** [comment] 2020-01-02 14:42
How can this not have been added yet? 
Please add format, similar to the "format" parameter in the Classic API's "/string/download"

**Comment by oleghnidets** [comment] 2020-07-27 11:48
Hi guys, 
Any updates on this? It would be great feature. It stops us of using API.

**Closed** 2021-12-20 11:41 UTC
Labels: enhancement
